# Generated by Django 5.2.13 on 2026-04-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('players', '0002_remove_player_alt_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('Man_of_the_Match', 'Man of the Match'), ('Work_Horse', 'Work Horse'), ('Playmaker', 'Playmaker'), ('Defensive_Wall', 'Defensive Wall'), ('Finisher', 'Finisher')], max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='match.match')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='players.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='players.player')),
            ],
            options={
                'unique_together': {('match', 'voter', 'vote_type')},
            },
        ),
    ]
