# Generated by Django 5.2.13 on 2026-04-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker')], max_length=20)),
                ('alt_position', models.CharField(blank=True, choices=[('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker')], max_length=20)),
                ('shooting', models.PositiveIntegerField(default=5)),
                ('passing', models.PositiveIntegerField(default=5)),
                ('defending', models.PositiveIntegerField(default=5)),
                ('stamina', models.PositiveIntegerField(default=5)),
                ('work_rate', models.PositiveIntegerField(default=5)),
                ('pace', models.PositiveIntegerField(default=5)),
                ('strength', models.PositiveIntegerField(default=5)),
                ('skills', models.PositiveIntegerField(default=5)),
                ('technical_ability', models.PositiveIntegerField(default=5)),
                ('match_winner', models.PositiveIntegerField(default=3)),
                ('rating', models.FloatField(default=65.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
