# Generated by Django 5.2.13 on 2026-04-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='alt_position',
        ),
    ]
