# Generated by Django 5.2.13 on 2026-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_alt_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defending',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='technical_ability',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.FloatField(default=5),
        ),
    ]
